version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - local

networks:
  local:
    name: local
    driver: bridge