---
name: Checks
on: [push]
jobs:
  test-lint:
    name: Tests and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Tests
        run: make test # docker compose run --rm sh -c "python manage.py test"
        
      - name: Lint Code
        run: make lint # docker compose run --rm sh -c flake8